import type { RecordId } from '@bt/shared/types';
import { Money } from '@common/types/money';
import cc from 'currency-codes';
import { z } from 'zod';

/**
 * Canonical record ID validator. Entity primary keys and in-scope foreign
 * keys are UUID strings; this is the single knob that controls the
 * accepted format on the API surface.
 *
 * Accepts any UUID version. New rows generated by the application are
 * UUIDv7 (time-ordered), but rows inserted by the migration backfill via
 * `gen_random_uuid()` are v4, and the nil UUID is used as a test sentinel.
 *
 * Returns a branded `RecordId` so downstream code is protected against
 * arithmetic coercion and cross-string mixups. Use this validator anywhere
 * an entity ID enters the system from the API surface.
 *
 * Users, Currencies, ExchangeRates, and MerchantCategoryCodes still use
 * integer keys and are out of scope for this validator.
 */
export const recordId = () => z.uuid().transform((v) => v as RecordId);
export const recordArrayIds = () => z.array(recordId());

/**
 * Array of unique record IDs. Validates that all IDs are unique.
 * Accepts optional min/max constraints.
 */
export const uniqueRecordIds = ({ min, max }: { min?: number; max?: number } = {}) => {
  let schema = z.array(recordId());
  if (min !== undefined) schema = schema.min(min);
  if (max !== undefined) schema = schema.max(max);
  return schema.refine((ids) => new Set(ids).size === ids.length, {
    message: 'IDs must be unique',
  });
};

/**
 * Zod type for decimal monetary amounts from API requests.
 * Accepts a finite number and transforms it directly into a Money instance,
 * eliminating the need to call Money.fromDecimal() manually in controllers.
 *
 * @example
 * body: z.object({
 *   amount: decimalMoney(),           // Money instance, any value
 *   fee: decimalMoney().optional(),   // optional Money instance
 * })
 */
export const decimalMoney = () => z.number().transform((val) => Money.fromDecimal(val));

/**
 * Canonical currency-code validator for API input.
 *
 * Normalizes to uppercase, then enforces membership in ISO 4217 via the
 * `currency-codes` dataset — the same source that seeds the Currencies
 * table — so an unknown code is rejected at the request boundary instead
 * of failing deeper against a foreign key or exchange-rate lookup.
 *
 * Precious-metal and test codes (XAU, XXX, …) are valid ISO 4217 and pass
 * here; contexts that need spendable-only currencies filter them out
 * separately via NON_CURRENCY_CODES.
 *
 * @example
 * body: z.object({
 *   currencyCode: currencyCode(),                       // "usd" => "USD"
 *   displayCurrencyCode: currencyCode().nullable().optional(),
 * })
 */
export const currencyCode = () =>
  z
    .string()
    .trim()
    .toUpperCase()
    .length(3)
    .refine((code) => cc.code(code) !== undefined, {
      message: 'Invalid currency code. Use an ISO 4217 code, e.g. "USD".',
    });

/**
 * Optional comma-separated record IDs for query parameters.
 * Silently filters out malformed (non-UUID) values for GET-query lenience.
 * Returns undefined when the string is absent.
 *
 * @example
 * query: z.object({ categoryIds: optionalCommaSeparatedIds() })
 * // "uuid1,uuid2,uuid3" => [uuid1, uuid2, uuid3]
 * // "uuid1,garbage,uuid2" => [uuid1, uuid2]
 * // undefined => undefined
 */
export const optionalCommaSeparatedIds = () => {
  const idSchema = recordId();
  return z
    .string()
    .optional()
    .transform((val) =>
      val
        ? val
            .split(',')
            .map((id) => id.trim())
            .filter((id) => idSchema.safeParse(id).success)
            .map((id) => id as RecordId)
        : undefined,
    );
};

/**
 * Used for the case when array is expected to be received like 1,2,3.
 * For example GET queries
 */
export const commaSeparatedRecordIds = z.string().transform((str, ctx) => {
  const idSchema = recordId();
  const ids = str.split(',').map((id) => {
    const result = idSchema.safeParse(id);
    return result.success ? result.data : null;
  });

  if (ids.some((id) => id === null)) {
    ctx.addIssue({
      code: z.ZodIssueCode.custom,
      message: 'Not all values are valid record IDs',
    });
    return z.NEVER;
  }
  return ids.filter((id): id is RecordId => id !== null);
});

/**
 * Properly handles boolean query parameters from URL strings.
 * Converts "true", "1" to true and "false", "0" to false.
 * Rejects other string values.
 */
export const booleanQuery = () =>
  z.union([z.boolean(), z.string()]).transform((val, ctx) => {
    if (typeof val === 'boolean') {
      return val;
    }

    const lowerVal = val.toLowerCase();
    if (lowerVal === 'true' || lowerVal === '1') {
      return true;
    }
    if (lowerVal === 'false' || lowerVal === '0') {
      return false;
    }

    ctx.addIssue({
      code: z.ZodIssueCode.custom,
      message: 'Boolean value must be "true", "false", "1", or "0"',
    });
    return z.NEVER;
  });

/** Validates the *shape* of a YYYY-MM-DD date string. For real-date checking use `dateBound`. */
export const dateString = () =>
  z.string().regex(/^\d{4}-\d{2}-\d{2}$/, { message: 'Date must be in YYYY-MM-DD format' });

/**
 * A real calendar day in `YYYY-MM-DD` form. Extends `dateString()` (which only
 * checks the shape) by rejecting regex-matching but non-existent dates such as
 * `2020-13-45` via `Date.parse`.
 */
const calendarDate = () => dateString().refine((value) => !Number.isNaN(Date.parse(value)), 'Invalid calendar date');

type DateRangePrecision = 'date' | 'datetime';

/**
 * A single date-range bound, validated to a `string`.
 *
 * - `precision: 'date'` (default) — strict `YYYY-MM-DD` real calendar day.
 * - `precision: 'datetime'` — ISO 8601 datetime. `offset: true` also permits a
 *   timezone offset (e.g. `+05:00`); otherwise only UTC (`Z`) is accepted.
 *
 * Use directly for a lone date field, or let {@link dateRange} pair two of these
 * with an ordering guard.
 */
export const dateBound = ({
  precision = 'date',
  offset = false,
}: { precision?: DateRangePrecision; offset?: boolean } = {}): z.ZodType<string> =>
  precision === 'datetime' ? z.string().datetime({ offset }) : calendarDate();

// Compares two bounds as instants, so it is correct for calendar days, UTC
// datetimes, and offset datetimes alike (each parses to a comparable epoch).
// A missing bound passes, so partial ranges are allowed. Bounds reaching this
// point are already format-validated, so `new Date` never yields NaN here.
const isOrderedPair = (from: unknown, to: unknown) =>
  from == null || to == null || new Date(from as string).getTime() <= new Date(to as string).getTime();

/**
 * Attaches the `from <= to` ordering guard to a `z.object` whose two bound
 * fields are named by `names` (default `['from', 'to']`). Pair it with a spread
 * `...dateRange()` or with `dateBound()` fields:
 *
 *   withDateOrder(z.object({ ...dateRange(), accountId: recordId().optional() }))
 *   withDateOrder(z.object({ startDate: dateBound(), endDate: dateBound().nullable().optional() }), ['startDate', 'endDate'])
 *
 * Throws at construction time if the wrapped object is missing either bound
 * field — otherwise the guard would silently pass everything (a no-op is a worse
 * failure than a loud one). This is why the ordering check lives in a separate
 * wrapper: a cross-field refine can't ride the `...dateRange()` spread, so the
 * two are joined here and validated together.
 */
export const withDateOrder = <T extends z.ZodTypeAny>(schema: T, names: readonly [string, string] = ['from', 'to']) => {
  // In Zod v4 `.refine()`/`.superRefine()` keep a ZodObject a ZodObject (checks
  // are stored inline, not wrapped), so `.shape` is still readable here.
  const shape = (schema as { shape?: Record<string, unknown> }).shape;
  const missing = shape ? names.filter((name) => !(name in shape)) : names;
  if (missing.length > 0) {
    throw new Error(
      `withDateOrder: wrapped object is missing bound field(s) [${missing.join(', ')}]. ` +
        `Spread \`...dateRange()\` or add \`dateBound()\` fields named [${names.join(', ')}]. ` +
        `Got: ${shape ? Object.keys(shape).join(', ') || '(no fields)' : 'not a ZodObject'}.`,
    );
  }
  return schema.refine(
    (data) =>
      isOrderedPair((data as Record<string, unknown>)?.[names[0]], (data as Record<string, unknown>)?.[names[1]]),
    { message: `\`${names[0]}\` must be on or before \`${names[1]}\``, path: [names[0]] },
  );
};

interface DateRangeFieldsConfig {
  /** `'date'` (default) → `YYYY-MM-DD`; `'datetime'` → ISO 8601 (see {@link dateBound}). */
  precision?: DateRangePrecision;
  /** Datetime only: allow a timezone offset. Default `false` (UTC `Z`). */
  offset?: boolean;
}

/**
 * A spreadable `{ from, to }` pair of date bounds — the sugar for the common
 * two-ended range. Spread it into a `z.object` next to your other fields, then
 * wrap with {@link withDateOrder} to enforce `from <= to`:
 *
 * @example
 * query: withDateOrder(z.object({ ...dateRange(), accountId: recordId().optional() }))          // optional YYYY-MM-DD
 * query: withDateOrder(z.object({ ...dateRange({ required: true, precision: 'datetime' }), granularity: z.enum([...]) }))
 * body:  z.object({ range: withDateOrder(z.object(dateRange())).optional() })                   // nested { from?, to? }
 *
 * Both bounds are optional by default; pass `{ required: true }` for both mandatory.
 * This helper always names the fields `from`/`to`. For a differently-named pair
 * (e.g. a domain entity's `startDate`/`endDate`) or asymmetric optionality (one
 * required, one nullable), build the fields with {@link dateBound} directly.
 */
export function dateRange(config: DateRangeFieldsConfig & { required: true }): {
  from: z.ZodType<string>;
  to: z.ZodType<string>;
};
export function dateRange(config?: DateRangeFieldsConfig & { required?: false }): {
  from: z.ZodOptional<z.ZodType<string>>;
  to: z.ZodOptional<z.ZodType<string>>;
};
export function dateRange(config: DateRangeFieldsConfig & { required?: boolean } = {}) {
  const { required = false, precision = 'date', offset = false } = config;
  const bound = dateBound({ precision, offset });
  return { from: required ? bound : bound.optional(), to: required ? bound : bound.optional() };
}

/** Validates a positive decimal amount string (rejects zero and negative by default). */
export const positiveAmountString = () =>
  z.string().refine((val) => !isNaN(parseFloat(val)) && parseFloat(val) > 0, {
    message: 'Amount must be a valid number greater than 0',
  });

export const numericString = (options?: { allowNegative?: boolean; allowZero?: boolean }) =>
  z
    .union([z.string(), z.number()])
    .refine(
      (val) => {
        const num = typeof val === 'string' ? parseFloat(val) : val;
        if (isNaN(num)) return false;
        if (!options?.allowZero && num === 0) return false;
        if (!options?.allowNegative && num < 0) return false;
        return true;
      },
      {
        message: 'Invalid number format',
      },
    )
    .transform((val) => String(val));

/**
 * Strict decimal string for monetary / arithmetic fields stored as decimal columns.
 * Accepts number or string, validates against `-?\d+(.\d+)?`, returns canonical string.
 * Use when a value will be persisted as a decimal and must round-trip without
 * floating-point lossiness or scientific notation. For pure `> 0` validation use
 * `positiveAmountString()` instead.
 */
export const decimalString = () =>
  z.union([z.string(), z.number()]).transform((v, ctx) => {
    const s = typeof v === 'number' ? v.toString() : v;
    if (!/^-?\d+(\.\d+)?$/.test(s)) {
      ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'Invalid decimal' });
      return z.NEVER;
    }
    return s;
  });

/**
 * Fractional percentage in [0, 1] (e.g. 0.085 = 8.5%). Accepts number or numeric
 * string, returns canonical string. Use for stored fee/carry/hurdle fractions where
 * the persisted value is the raw fraction, not the display percent.
 */
export const percentageFraction = () =>
  z.coerce
    .number()
    .min(0)
    .max(1)
    .transform((v) => v.toString());
