import type { RecordId } from '@bt/shared/types';
import { Money } from '@common/types/money';
import cc from 'currency-codes';
import { z } from 'zod';

/**
 * Canonical record ID validator. Entity primary keys and in-scope foreign
 * keys are UUID strings; this is the single knob that controls the
 * accepted format on the API surface.
 *
 * Accepts any UUID version. New rows generated by the application are
 * UUIDv7 (time-ordered), but rows inserted by the migration backfill via
 * `gen_random_uuid()` are v4, and the nil UUID is used as a test sentinel.
 *
 * Returns a branded `RecordId` so downstream code is protected against
 * arithmetic coercion and cross-string mixups. Use this validator anywhere
 * an entity ID enters the system from the API surface.
 *
 * Users, Currencies, ExchangeRates, and MerchantCategoryCodes still use
 * integer keys and are out of scope for this validator.
 */
export const recordId = () => z.uuid().transform((v) => v as RecordId);
export const recordArrayIds = () => z.array(recordId());

/**
 * Array of unique record IDs. Validates that all IDs are unique.
 * Accepts optional min/max constraints.
 */
export const uniqueRecordIds = ({ min, max }: { min?: number; max?: number } = {}) => {
  let schema = z.array(recordId());
  if (min !== undefined) schema = schema.min(min);
  if (max !== undefined) schema = schema.max(max);
  return schema.refine((ids) => new Set(ids).size === ids.length, {
    message: 'IDs must be unique',
  });
};

/**
 * Zod type for decimal monetary amounts from API requests.
 * Accepts a finite number and transforms it directly into a Money instance,
 * eliminating the need to call Money.fromDecimal() manually in controllers.
 *
 * @example
 * body: z.object({
 *   amount: decimalMoney(),           // Money instance, any value
 *   fee: decimalMoney().optional(),   // optional Money instance
 * })
 */
export const decimalMoney = () => z.number().transform((val) => Money.fromDecimal(val));

/**
 * Canonical currency-code validator for API input.
 *
 * Normalizes to uppercase, then enforces membership in ISO 4217 via the
 * `currency-codes` dataset — the same source that seeds the Currencies
 * table — so an unknown code is rejected at the request boundary instead
 * of failing deeper against a foreign key or exchange-rate lookup.
 *
 * Precious-metal and test codes (XAU, XXX, …) are valid ISO 4217 and pass
 * here; contexts that need spendable-only currencies filter them out
 * separately via NON_CURRENCY_CODES.
 *
 * @example
 * body: z.object({
 *   currencyCode: currencyCode(),                       // "usd" => "USD"
 *   displayCurrencyCode: currencyCode().nullable().optional(),
 * })
 */
export const currencyCode = () =>
  z
    .string()
    .trim()
    .toUpperCase()
    .length(3)
    .refine((code) => cc.code(code) !== undefined, {
      message: 'Invalid currency code. Use an ISO 4217 code, e.g. "USD".',
    });

/**
 * Optional comma-separated record IDs for query parameters.
 * Silently filters out malformed (non-UUID) values for GET-query lenience.
 * Returns undefined when the string is absent.
 *
 * @example
 * query: z.object({ categoryIds: optionalCommaSeparatedIds() })
 * // "uuid1,uuid2,uuid3" => [uuid1, uuid2, uuid3]
 * // "uuid1,garbage,uuid2" => [uuid1, uuid2]
 * // undefined => undefined
 */
export const optionalCommaSeparatedIds = () => {
  const idSchema = recordId();
  return z
    .string()
    .optional()
    .transform((val) =>
      val
        ? val
            .split(',')
            .map((id) => id.trim())
            .filter((id) => idSchema.safeParse(id).success)
            .map((id) => id as RecordId)
        : undefined,
    );
};

/**
 * Used for the case when array is expected to be received like 1,2,3.
 * For example GET queries
 */
export const commaSeparatedRecordIds = z.string().transform((str, ctx) => {
  const idSchema = recordId();
  const ids = str.split(',').map((id) => {
    const result = idSchema.safeParse(id);
    return result.success ? result.data : null;
  });

  if (ids.some((id) => id === null)) {
    ctx.addIssue({
      code: z.ZodIssueCode.custom,
      message: 'Not all values are valid record IDs',
    });
    return z.NEVER;
  }
  return ids.filter((id): id is RecordId => id !== null);
});

/**
 * Properly handles boolean query parameters from URL strings.
 * Converts "true", "1" to true and "false", "0" to false.
 * Rejects other string values.
 */
export const booleanQuery = () =>
  z.union([z.boolean(), z.string()]).transform((val, ctx) => {
    if (typeof val === 'boolean') {
      return val;
    }

    const lowerVal = val.toLowerCase();
    if (lowerVal === 'true' || lowerVal === '1') {
      return true;
    }
    if (lowerVal === 'false' || lowerVal === '0') {
      return false;
    }

    ctx.addIssue({
      code: z.ZodIssueCode.custom,
      message: 'Boolean value must be "true", "false", "1", or "0"',
    });
    return z.NEVER;
  });

/** Validates a YYYY-MM-DD date string. */
export const dateString = () =>
  z.string().regex(/^\d{4}-\d{2}-\d{2}$/, { message: 'Date must be in YYYY-MM-DD format' });

/**
 * Optional date range with calendar-day boundaries (YYYY-MM-DD).
 * Both ends are optional; the cross-field check rejects ranges where `from`
 * is after `to` only when both are present. String comparison is sound because
 * ISO YYYY-MM-DD sorts lexicographically the same way it sorts chronologically.
 *
 * Each endpoint additionally rejects regex-matching but non-real calendar dates
 * (e.g. `2020-13-45`) via `Date.parse` — `dateString()` alone does not.
 */
export const dateRange = () => {
  const calendarDate = dateString().refine((value) => !Number.isNaN(Date.parse(value)), 'Invalid calendar date');
  return z
    .object({
      from: calendarDate.optional(),
      to: calendarDate.optional(),
    })
    .refine(({ from, to }) => !from || !to || from <= to, {
      message: '`from` must be on or before `to`',
      path: ['from'],
    });
};

/** Validates a positive decimal amount string (rejects zero and negative by default). */
export const positiveAmountString = () =>
  z.string().refine((val) => !isNaN(parseFloat(val)) && parseFloat(val) > 0, {
    message: 'Amount must be a valid number greater than 0',
  });

export const numericString = (options?: { allowNegative?: boolean; allowZero?: boolean }) =>
  z
    .union([z.string(), z.number()])
    .refine(
      (val) => {
        const num = typeof val === 'string' ? parseFloat(val) : val;
        if (isNaN(num)) return false;
        if (!options?.allowZero && num === 0) return false;
        if (!options?.allowNegative && num < 0) return false;
        return true;
      },
      {
        message: 'Invalid number format',
      },
    )
    .transform((val) => String(val));

/**
 * Strict decimal string for monetary / arithmetic fields stored as decimal columns.
 * Accepts number or string, validates against `-?\d+(.\d+)?`, returns canonical string.
 * Use when a value will be persisted as a decimal and must round-trip without
 * floating-point lossiness or scientific notation. For pure `> 0` validation use
 * `positiveAmountString()` instead.
 */
export const decimalString = () =>
  z.union([z.string(), z.number()]).transform((v, ctx) => {
    const s = typeof v === 'number' ? v.toString() : v;
    if (!/^-?\d+(\.\d+)?$/.test(s)) {
      ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'Invalid decimal' });
      return z.NEVER;
    }
    return s;
  });

/**
 * Fractional percentage in [0, 1] (e.g. 0.085 = 8.5%). Accepts number or numeric
 * string, returns canonical string. Use for stored fee/carry/hurdle fractions where
 * the persisted value is the raw fraction, not the display percent.
 */
export const percentageFraction = () =>
  z.coerce
    .number()
    .min(0)
    .max(1)
    .transform((v) => v.toString());
