name: Prepare local environment
description: Prepare local environment by setting up Bun and caching dependencies
outputs:
  cache-hit:
    description: Whether the dependencies were cached
    value: ${{ steps.bun-cache.outputs.cache-hit }}
runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
    - uses: actions/cache@v4
      id: bun-cache
      with:
        path: |
          **/node_modules
          ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock', '**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-bun-
