import { DataTypes, QueryInterface, Transaction } from 'sequelize';

module.exports = {
  up: async (queryInterface: QueryInterface): Promise<void> => {
    const t: Transaction = await queryInterface.sequelize.transaction();

    try {
      // accountId: which account a generated transaction will be booked against.
      // Nullable so existing reminders (and reminders that don't auto-generate
      // transactions) remain valid. SET NULL on account delete keeps the reminder
      // alive but unlinked.
      await queryInterface.addColumn(
        'PaymentReminders',
        'accountId',
        {
          type: DataTypes.UUID,
          allowNull: true,
          references: { model: 'Accounts', key: 'id' },
          onUpdate: 'CASCADE',
          onDelete: 'SET NULL',
        },
        { transaction: t },
      );

      // maxOccurrences: cap on how many periods a recurring reminder generates.
      // Null = repeat indefinitely. When set it must be >= 1.
      await queryInterface.addColumn(
        'PaymentReminders',
        'maxOccurrences',
        {
          type: DataTypes.SMALLINT,
          allowNull: true,
          comment: 'Installment count: stop generating periods after this many. Null = indefinite.',
        },
        { transaction: t },
      );

      await queryInterface.sequelize.query(
        `ALTER TABLE "PaymentReminders" ADD CONSTRAINT "chk_payment_reminders_max_occurrences"
         CHECK ("maxOccurrences" IS NULL OR "maxOccurrences" >= 1);`,
        { transaction: t },
      );

      // type: subscription | bill. Stored as VARCHAR with a TS-side enum
      // (SUBSCRIPTION_TYPES), not a DB enum. Purely a UI filter/label — both types
      // run on the same engine. The only behavioural rule is that a subscription
      // must carry an expected amount while a bill may be variable; existing
      // amount-less reminders are therefore backfilled as 'bill'.
      await queryInterface.addColumn(
        'PaymentReminders',
        'type',
        {
          type: DataTypes.STRING(50),
          allowNull: false,
          defaultValue: 'subscription',
        },
        { transaction: t },
      );

      await queryInterface.sequelize.query(
        `UPDATE "PaymentReminders" SET "type" = 'bill' WHERE "expectedAmount" IS NULL;`,
        {
          transaction: t,
        },
      );

      // showInWidget: whether this item appears in the dashboard "Subscriptions &
      // Bills" widget. Defaults true; users opt non-deterministic items (e.g. a
      // variable tax) out so they don't distort the widget's projected total.
      await queryInterface.addColumn(
        'PaymentReminders',
        'showInWidget',
        {
          type: DataTypes.BOOLEAN,
          allowNull: false,
          defaultValue: true,
        },
        { transaction: t },
      );

      // transactionAutoCreated: marks whether the period's linked transaction was
      // generated by the app (CREATE-mode "I paid") rather than supplied by the user
      // (LINK-mode). Reverting a paid period deletes an app-generated transaction to
      // restore the account balance, but must never delete a user's own linked one.
      await queryInterface.addColumn(
        'PaymentReminderPeriods',
        'transactionAutoCreated',
        {
          type: DataTypes.BOOLEAN,
          allowNull: false,
          defaultValue: false,
        },
        { transaction: t },
      );

      await t.commit();
    } catch (error) {
      await t.rollback();
      throw error;
    }
  },

  down: async (queryInterface: QueryInterface): Promise<void> => {
    const t: Transaction = await queryInterface.sequelize.transaction();

    try {
      await queryInterface.removeColumn('PaymentReminderPeriods', 'transactionAutoCreated', { transaction: t });

      await queryInterface.removeColumn('PaymentReminders', 'showInWidget', { transaction: t });

      await queryInterface.removeColumn('PaymentReminders', 'type', { transaction: t });

      await queryInterface.sequelize.query(
        `ALTER TABLE "PaymentReminders" DROP CONSTRAINT IF EXISTS "chk_payment_reminders_max_occurrences";`,
        { transaction: t },
      );

      await queryInterface.removeColumn('PaymentReminders', 'maxOccurrences', { transaction: t });

      // removeColumn drops the dependent FK constraint along with the column.
      await queryInterface.removeColumn('PaymentReminders', 'accountId', { transaction: t });

      await t.commit();
    } catch (error) {
      await t.rollback();
      throw error;
    }
  },
};
