name: Build frontend Docker image
description: Build and optionally push the frontend Docker image

inputs:
  vps-host:
    description: 'VPS_HOST'
    required: true
  vue-app-api-ver:
    description: 'VUE_APP_API_VER'
    required: true
  docker-hub-username:
    description: 'DOCKER_HUB_USERNAME'
    required: true
  docker-hub-access-token:
    description: 'DOCKER_HUB_ACCESS_TOKEN'
    required: true
  push:
    description: Specifies if docker result should be pushed
    required: false
    default: 'false'
outputs:
  docker-build-digest:
    description: Docker build digest
    value: ${{ steps.docker-build.outputs.digest }}
runs:
  using: composite
  steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_VITE_APP_API_HTTP: https://${{ inputs.vps-host }}
        envkey_VITE_APP_API_VER: ${{ inputs.vue-app-api-ver }}
        directory: ./
        file_name: .env.production

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.docker-hub-username }}
        password: ${{ inputs.docker-hub-access-token }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build
      id: docker-build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./docker/prod/frontend/Dockerfile
        push: ${{ inputs.push == 'true' }}
        load: ${{ inputs.push != 'true' }}
        tags: ${{ inputs.docker-hub-username }}/budget-tracker-fe:latest
